/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.industrialmaster.lms.view;

import com.industrialmaster.lms.control.DepositsController;
import com.industrialmaster.lms.model.Deposits;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MN
 */
public class DepositsPanel extends javax.swing.JPanel {
int id;
    /**
     * Creates new form DepositsPanel
     */
    public DepositsPanel() {
        initComponents();
        loadToTable();
    }
    
    
     public void loadToTable(){

try{
    List<Deposits> list = DepositsController.getAll(); // Controller eken data genna ganima
    DefaultTableModel dtm =(DefaultTableModel) tblDeposits.getModel();
    dtm.setRowCount(0);
    for(Deposits t:list){
    Object[] row = {t.getId(),t.getUser_id(), t.getCopy_id(),t.getDeposit_date(),t.getDue_date()};
    dtm.addRow(row);
    }
}catch(Exception e){
    
}}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUser_id = new javax.swing.JTextField();
        txtCopy_id = new javax.swing.JTextField();
        txtDeposits_date = new javax.swing.JTextField();
        txtDue_date = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeposits = new javax.swing.JTable();

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");

        jLabel1.setText("User id");

        jLabel2.setText("Copy id");

        jLabel3.setText("Deposits date");

        jLabel4.setText("Due date");

        txtCopy_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCopy_idActionPerformed(evt);
            }
        });

        tblDeposits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "User_id", "Copy_id", "Deposits_date", "Due_date"
            }
        ));
        tblDeposits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDepositsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDeposits);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addGap(88, 88, 88)
                        .addComponent(btnSearch))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUser_id, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(txtCopy_id)
                            .addComponent(txtDeposits_date)
                            .addComponent(txtDue_date))))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser_id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCopy_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeposits_date, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDue_date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCopy_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCopy_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCopy_idActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String user_id=txtUser_id.getText();
        String copy_id=txtCopy_id.getText();
       String deposit_date = txtDeposits_date.getText();
       String due_date = txtDue_date.getText();
       
       
       
       //2.Process data before store
       //a. Validations

       
       
       //b. Generate Data (Non fillables)
      
       
       Deposits deposit = new Deposits();
        deposit.setUser_id(user_id);
       deposit.setCopy_id(copy_id);
       deposit.setDeposit_date(deposit_date);
        deposit.setDue_date(due_date);
       
      
       
      boolean done = DepositsController.save(deposit);
       if(done){
       JOptionPane.showMessageDialog(this,"Saved");
       }else{
       JOptionPane.showMessageDialog(this,"Error");
       }
       
       loadToTable();
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         String user_id=txtUser_id.getText();
        String copy_id=txtCopy_id.getText();
       String deposit_date = txtDeposits_date.getText();
       String due_date = txtDue_date.getText();
      
       
       //2.Process data before store
       //a. Validations
     
       
       
       //b. Generate Data (Non fillables)
       
         Deposits deposit = new Deposits();
        deposit.setUser_id(user_id);
       deposit.setCopy_id(copy_id);
       deposit.setDeposit_date(deposit_date);
        deposit.setDue_date(due_date);
      
      
       // click krn row eke id eka me variable ekt save krl thiyagannava
       
      boolean done = DepositsController.update(deposit);
       if(done){
       JOptionPane.showMessageDialog(this,"Updated");
       }else{
       JOptionPane.showMessageDialog(this,"Error");
       }
        
        
        loadToTable();
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblDepositsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDepositsMouseClicked
        // TODO add your handling code here:
           int row = tblDeposits.getSelectedRow();
       if(row!=-1){//if the row selected
       
           String idstr= tblDeposits.getValueAt(row, 0).toString();
           id = Integer.parseInt(idstr);
           Deposits deposits = DepositsController.getOne(id);
           txtUser_id.setText(deposits.getUser_id()+"");
           txtCopy_id.setText(deposits.getCopy_id());
           txtDeposits_date.setText(deposits.getDeposit_date()+"");
           txtDue_date.setText(deposits.getDue_date()+"");
         
       }
        
    }//GEN-LAST:event_tblDepositsMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         DepositsController.delete(id);
        loadToTable();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDeposits;
    private javax.swing.JTextField txtCopy_id;
    private javax.swing.JTextField txtDeposits_date;
    private javax.swing.JTextField txtDue_date;
    private javax.swing.JTextField txtUser_id;
    // End of variables declaration//GEN-END:variables
}
